name: C++26 Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t cpp26-app .

      - name: Run tests in Docker container
        run: |
          docker run --rm cpp26-app /bin/bash -c "cd /workspace && cmake -B build"